### ISSUE TITLE
Yalan oldu aşkımız

### ISSUE THREAD

**Issue by frknbasaran** [mavidurak/askMe#1]
neden yalan oldu? ey community neredesiniz

**Comment by erayarslan** [comment]
utanmadan bi de bi projenin neden "yalan olmasına" mı nida vuruyorsun, ey kozmişov.

**Comment by gormelof** [comment]
yalan olmasın yapalım hemen

**Comment by frknbasaran** [comment]
Gemi biraz sola mı çekiyo

**Comment by finderskeepers** [comment]
neyse ya bi ara şaaparız diye rafa kaldırmıştınız, hatırlatırım...

2015-10-09 13:31 GMT+02:00 Furkan Başaran notifications@github.com:

**Comment by finderskeepers** [comment]
ne gemisi abi?

**Comment by erayarslan** [comment]
![tava](https://cloud.githubusercontent.com/assets/1534649/10427854/99e06abe-70f5-11e5-9690-07e4dfa1662a.png)

**Comment by kurkix** [comment]
meraba abiler

**Comment by ucenmi9254** [comment]
bundan nasıl çıkıyoz :D

2015-10-12 19:38 GMT+03:00 kurkix notifications@github.com:

**Comment by erayarslan** [comment]
GitHub'dan bak buraya sağ üstten Notifications > Unsubscribe.

**Comment by ucenmi9254** [comment]
gördüm panpa 1 haftadır hastenedeydim sürekl bunlar gelince deli oluyor insan :dancers:

**Comment by finderskeepers** [comment]
http://imgim.com/bak-surdan-siktir-git.jpg

**Comment by Alpereny** [comment]
burada yazılanları okumadan güne başlayamıyorum
